### ISSUE TITLE
split_function throws IndexError

### ISSUE THREAD

**Issue by proski** [rferrazz/pyqt4topyqt5#3]
Example

    from PyQt4.QtCore import QSettings
    foo().connect(bar)

`i` in incremented and `function[i]` is accessed without checking if the index is valid.

It appears that `fun_re` fails to produce the match expected by `split_function`. It would be helpful to have comments about the intention of the code.

**Comment by mclam009** [comment]
This issue has been resolved with the latest update in which split_function was reworked.

**Comment by rferrazz** [comment]
Issue resolved by adf1d4d6abc733053c1bd5f58f3a276230d53ce6
